import csv
import random
import os
from datetime import datetime

OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
os.makedirs(OUT_DIR, exist_ok=True)

CITY = 'Chennai'
LAT_MIN, LAT_MAX = 13.0, 13.2
LON_MIN, LON_MAX = 80.0, 80.4

first_names = [
    'Arjun','Karthik','Priya','Ananya','Vikram','Suresh','Deepa','Ramesh','Lakshmi','Naveen',
    'Divya','Mani','Kavya','Vijay','Senthil','Meena','Raja','Ajith','Sruthi','Bhavani'
]
last_names = [
    'Kumar','Iyer','Sharma','Natarajan','Rao','Subramanian','Krishnan','Reddy','Nair','Das'
]
streets = [
    'Anna Salai','T. Nagar','Adyar','Velachery','Old Mahabalipuram Road','Guindy','Mylapore','Thiruvanmiyur',
    'Greams Road','Nungambakkam','Ambattur','Purasaiwakkam'
]

email_domains = ['example.com','mail.com','testmail.com','gmail.com']

phone_prefixes = ['9840','9841','9842','9843','9844','9444','9790','9003']

random.seed(42)

def rand_coord():
    return round(random.uniform(LAT_MIN, LAT_MAX), 6), round(random.uniform(LON_MIN, LON_MAX), 6)

def gen_mobile():
    return random.choice(phone_prefixes) + ''.join(str(random.randint(0,9)) for _ in range(6))

def gen_email(name, idx):
    local = name.lower().replace(' ', '.')
    return f"{local}{idx}@{random.choice(email_domains)}"


def gen_users(n, start_id=1):
    rows = []
    for i in range(start_id, start_id+n):
        fn = random.choice(first_names)
        ln = random.choice(last_names)
        name = f"{fn} {ln}"
        mobile = gen_mobile()
        email = gen_email(name, i)
        addr = f"{random.randint(10,250)} {random.choice(streets)}, {random.choice(['East','West','North','South'])} Chennai"
        lat, lon = rand_coord()
        created = datetime.utcnow().isoformat()
        rows.append({
            'id': i,
            'name': name,
            'email': email,
            'mobile': mobile,
            'address': addr,
            'city': CITY,
            'latitude': lat,
            'longitude': lon,
            'created_at': created
        })
    return rows


def gen_homemakers(n, start_id=1):
    rows = []
    for i in range(start_id, start_id+n):
        fn = random.choice(first_names)
        ln = random.choice(last_names)
        owner = f"{fn} {ln}"
        shop = f"{ln} Kitchen"
        mobile = gen_mobile()
        email = gen_email(owner, i)
        rating = round(random.uniform(3.0, 5.0),2)
        addr = f"{random.randint(1,200)}, {random.choice(streets)}, Chennai"
        lat, lon = rand_coord()
        rows.append({
            'id': i,
            'owner_name': owner,
            'shop_name': shop,
            'email': email,
            'mobile': mobile,
            'rating': rating,
            'address': addr,
            'city': CITY,
            'latitude': lat,
            'longitude': lon
        })
    return rows


def gen_admins(n, start_id=1):
    roles = ['SUPERADMIN','ADMIN']
    rows = []
    for i in range(start_id, start_id+n):
        name = f"Admin {i}"
        email = f"admin{i}@example.com"
        mobile = gen_mobile()
        role = roles[i % len(roles)]
        rows.append({'id': i, 'name': name, 'email': email, 'mobile': mobile, 'role': role})
    return rows


def gen_delivery_executives(n, start_id=1):
    rows = []
    for i in range(start_id, start_id+n):
        fn = random.choice(first_names)
        ln = random.choice(last_names)
        name = f"{fn} {ln}"
        mobile = gen_mobile()
        email = gen_email(name, i)
        aadhar = ''.join(str(random.randint(0,9)) for _ in range(12))
        license_no = f"DL{random.randint(10,99)}{random.randint(1000000,9999999)}"
        vehicle_no = f"TN{random.randint(1,99)}-{random.randint(1000,9999)}"
        online = random.choice([True, False])
        lat, lon = rand_coord()
        rows.append({
            'id': i,
            'name': name,
            'email': email,
            'mobile': mobile,
            'aadhar_no': aadhar,
            'license_no': license_no,
            'vehicle_no': vehicle_no,
            'online': online,
            'city': CITY,
            'latitude': lat,
            'longitude': lon
        })
    return rows


def write_csv(filename, fieldnames, rows):
    path = os.path.join(OUT_DIR, filename)
    with open(path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
    print('Wrote', path)
    return path


def write_sql(path, users, homemakers, admins, executives):
    with open(path, 'w', encoding='utf-8') as f:
        f.write('-- Seed SQL generated by generate_seed_data.py\n')
        f.write('-- Users\n')
        for u in users:
            f.write("INSERT INTO users (id, name, email, mobile, address, city, latitude, longitude, created_at) VALUES (")
            f.write(f"{u['id']}, '{u['name'].replace("'","''")}', '{u['email']}', '{u['mobile']}', '{u['address'].replace("'","''")}', '{u['city']}', {u['latitude']}, {u['longitude']}, '{u['created_at']}'");
            f.write(");\n")
        f.write('\n-- Homemakers\n')
        for h in homemakers:
            f.write(f"INSERT INTO homemakers (id, owner_name, shop_name, email, mobile, rating, address, city, latitude, longitude) VALUES ({h['id']}, '{h['owner_name'].replace("'","''")}', '{h['shop_name'].replace("'","''")}', '{h['email']}', '{h['mobile']}', {h['rating']}, '{h['address'].replace("'","''")}', '{h['city']}', {h['latitude']}, {h['longitude']});\n")
        f.write('\n-- Admins\n')
        for a in admins:
            f.write(f"INSERT INTO admins (id, name, email, mobile, role) VALUES ({a['id']}, '{a['name']}', '{a['email']}', '{a['mobile']}', '{a['role']}');\n")
        f.write('\n-- Delivery Executives\n')
        for d in executives:
            f.write(f"INSERT INTO delivery_executives (id, name, email, mobile, aadhar_no, license_no, vehicle_no, online, city, latitude, longitude) VALUES ({d['id']}, '{d['name'].replace("'","''")}', '{d['email']}', '{d['mobile']}', '{d['aadhar_no']}', '{d['license_no']}', '{d['vehicle_no']}', {1 if d['online'] else 0}, '{d['city']}', {d['latitude']}, {d['longitude']});\n")
    print('Wrote', path)


if __name__ == '__main__':
    users = gen_users(500, start_id=1)
    homemakers = gen_homemakers(100, start_id=1)
    admins = gen_admins(3, start_id=1)
    executives = gen_delivery_executives(50, start_id=1)

    u_fields = ['id','name','email','mobile','address','city','latitude','longitude','created_at']
    h_fields = ['id','owner_name','shop_name','email','mobile','rating','address','city','latitude','longitude']
    a_fields = ['id','name','email','mobile','role']
    d_fields = ['id','name','email','mobile','aadhar_no','license_no','vehicle_no','online','city','latitude','longitude']

    write_csv('users_chennai.csv', u_fields, users)
    write_csv('homemakers_chennai.csv', h_fields, homemakers)
    write_csv('admins_chennai.csv', a_fields, admins)
    write_csv('delivery_executives_chennai.csv', d_fields, executives)

    sql_path = os.path.join(OUT_DIR, 'seed_chennai.sql')
    write_sql(sql_path, users, homemakers, admins, executives)

    print('\nGenerated:')
    print('- users_chennai.csv (500)')
    print('- homemakers_chennai.csv (100)')
    print('- admins_chennai.csv (3)')
    print('- delivery_executives_chennai.csv (50)')
    print('- seed_chennai.sql')
